################################################################################
# ==> Main Tasks for soa-domain Role
# ==> Creates a Domain with Fussion Middleware 12c R2 Infrastructure software
################################################################################

# ==> Create new domain
- name: copy AIAFP Libraries
  copy:
    src: "{{ software_library }}/{{aiafp_installer}}"
    dest: "{{ mw_installer_folder }}/"
  tags:
    - install-aiafp

- name: copy aiafp response file
  template: src=FPAIA.rsp dest={{ mw_installer_folder }}
  tags:
    - install-aiafp

- name: install aiafp component
  become_user: "{{ oracle_user }}"
  command: /bin/sh -c "{{ jdk_folder }}/bin/java -Xms1024m -Xmx1024m -jar {{ mw_installer_folder }}/aiafp_installer -silent -responseFile {{ mw_installer_folder }}/FPAIA.rsp -invPtrLoc {{ mw_installer_folder }}/oraInst.loc"
  tags:
    - install-aiafp
- name: copy domain configuration file for AIA Installation
  become_user: "{{ oracle_user }}"
  command: "{{ aia_home }}/comms_home/src/SCEApp/SCEApp.sh {{ middleware_home }}"
